### ISSUE TITLE
Supported BeatSaber versions and mods list

### ISSUE THREAD

**Issue by jcz1** [bsmg/ModAssistant#132]
Hello.

Please, is it possible to show supported BS versions (on main page)?
And mods list?

How to find out when it is safe to upgrade (1.9)?

Thanks.

**Comment by Assistant** [comment]
Knowing when it is safe to upgrade is tricky, since everyone has a very different definition of safe. 
You can check BeatMods directly to see which mods are supported on each version, and [this file](https://alias.beatmods.com/aliases.json) to see what versions are considered to be identical to others regarding modding.

**Comment by jcz1** [comment]
I think MA knows what versions of BS supports. And also knows what mods can install for upper BS versions. So i think it's possible to make list of installed AND supported mods after update.

**Comment by Assistant** [comment]
It is, however, showing this information is a bit trickier. I can't just show a list of supported version because that doesn't mean anything, since right after an update it would support the new version, regardless of if there's mods available or not. And to show a list of the mods that are supported I would need to make a new page.
