### ISSUE TITLE
Malware detected

### ISSUE THREAD

**Issue by EduCCF** [bsmg/ModAssistant#423]
MaxSecure detects that the ModAssistant.exe file act as a "Trojan Malware 300983".

Can anyone shed some light about this?

**Comment by Assistant** [comment]
It's a false positive, after giving a pass through [VirusTotal](https://www.virustotal.com/gui/file/cdcf777a4c9ac56ccc7f3faae79224f3d59c654d897d9add8af7162c3cc3d287/detection) you can see that MaxSecure is the only antivirus that detects it as malicious, and some googling revealed that MaxSecure often gives out false positives.
Since the source code is available, you can check that it does nothing malicious, and since the executable is compiled and posted by Github itself (which is run by Microsoft), you can be reasonably certain that it is what the source code says it is.
Since the executable isn't signed because signing certificates cost money, and it downloads files from the internet (the mods you're installing and updates), overzealous antiviruses sometimes find that suspicious and flag it as malware.
