### ISSUE TITLE
BSIPA does not update

### ISSUE THREAD

**Issue by ByteAlex** [bsmg/ModAssistant#74]
Hi,

after running Mod-Assistant 1.0.28 with selected Game-Version 1.6.1 and doing "Install" with latest updates, the "Installed" version of BSIPA always goes back to 3.12.23 (latest 3.13.7), even after running Mod-Assistant in Administrator Mode.

**Comment by WhiteZeroX** [comment]
Same here. But it must just be reading the current version incorrectly. Because I manually updated to 3.13.7 and Mod Assistant still thinks its 3.12.2

**Comment by Sam599** [comment]
I have solved this issue in my Mod Assistant by: Opening the Mod Assistant -> Going to "Options" -> Clicking in "Uninstall BSIPA" -> Then going in Mods -> Clicking in "Install or Update".

But for me even with the BSIPA updated it wasnt running my mods in game, so instead of only "Uninstall BSIPA", i clicked in "Remove All Mods" and then "Install or Update" to reinstall all my mods, then it worked.

**Comment by Corgiboy2** [comment]
> I have solved this issue in my Mod Assistant by: Opening the Mod Assistant -> Going to "Options" -> Clicking in "Uninstall BSIPA" -> Then going in Mods -> Clicking in "Install or Update".
> 
> But for me even with the BSIPA updated it wasnt running my mods in game, so instead of only "Uninstall BSIPA", i clicked in "Remove All Mods" and then "Install or Update" to reinstall all my mods, then it worked.

thank you so much sam this helped
